server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8081
  #address: 192.168.132.96


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scout_compass_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    show-sql: true
logging:
  file:
    name: ./apilogs/scout-compass-api.log









